server:
  host: "0.0.0.0"
  port: 8080

logging:
  level: "info"
  format: "json"

metrics:
  collection:
    default_interval: "60s"

packages:
  - owner: "d0ugal"
    repo: "filesystem-exporter"
  - owner: "d0ugal"
    # repo not specified - will discover all packages for owner
