server:
  host: "0.0.0.0"
  port: 8080

logging:
  level: "info"
  format: "json"

metrics:
  collection:
    default_interval: "60s"

packages:
  filesystem-exporter:
    owner: "d0ugal"
    repo: "filesystem-exporter"
    package_name: "filesystem-exporter"
    interval: "300s"  # 5 minutes
